### ISSUE TITLE
some confusions

### ISSUE THREAD

**Issue by elephanttt** [sbelharbi/deep-wsl-histo-min-max-uncertainty#4]
hi, I have a question. Why the size_const_cancer loss used for cancerous areas in the camelyon16 dataset, rather than size_const loss?

**Comment by sbelharbi** [comment]
hi,
cancer loss pushes the cancer to emerge over positive samples.
background loss is missing because it is already applied over negative samples to learn what is a background.
applying background loss over positive samples will further push the network to favor more background.
so, we learn background from negative samples, and we constraint cancer to be large on positive samples.

thanks

**Comment by elephanttt** [comment]
thanks
